### ISSUE TITLE
Error dragging custom file in

### ISSUE THREAD

**Issue by dmitriylyner** [helion3/inspire-tree-dom#16]
Is there a hook somewhere to override the onDrop function to allow for uploading your own custom file?
When I attempt to do so (by dropping a file from os x finder) I receive an error because the onDrop function expects is to be an existing tree node.
I would like to have control when a file from the os is dragged in but defer to the existing onDrop when a file within the tree is moved around.

![image](https://user-images.githubusercontent.com/3218659/38829296-d5bfbe7e-4175-11e8-94b4-6c92bb57621b.png)

Attempted something like `treeDom._tree.on('node.drop', function (event, node, handler) {
        event.preventTreeDefault();
      });` 
but the onDrop handler in listItem gets called first.

**Comment by viveleroi** [comment]
I've pushed a fix for this. Internally, the logic didn't account for non-nodes being dropped which it should, so I've corrected that.

When anything else is dropped, you'll receive the same `node.drop` event, but the `newNode` and `newIndex` args will be undefined.

The rest should work as expected - the target node highlights, etc.
