### ISSUE TITLE
Checkboxes render poorly in Firefox Quantum

### ISSUE THREAD

**Issue by KeithScheiwiller** [helion3/inspire-tree-dom#19]
Browser:
Firefox Quantum 60.0.1

Steps to reproduce:
1) Load any tree with checkboxes in Firefox Quantum. For example http://www.inspire-tree.com/demos/checkboxes.html
2) Notice styling of checkboxes places them off-center from the relevant nodes

![screenshot-2018-5-30 inspire tree - javascript ui tree component](https://user-images.githubusercontent.com/13041005/40747312-82558fc8-6422-11e8-96fc-cc49d8861a8c.png)

**Comment by viveleroi** [comment]
I can't reproduce this. I tried Firefox 60.0.1 64-bit on both macOS and Windows 10 and they show correctly.

That black checkbox outline is odd - I don't use anything like that natively.

**Comment by KeithScheiwiller** [comment]
Ya, it dawned on me that it must be due to GTK or similar, and thus nothing that can be fixed here.
Sorry about that.
