### ISSUE TITLE
'node.drop' event does not emit correct target

### ISSUE THREAD

**Issue by yjchen** [helion3/inspire-tree-dom#20]
The API document says:

     node.drop - (DragEvent event, TreeNode source, TreeNode target, int index) - Node was dropped. If target null, node was dropped into the root context.

My understanding is that target node is the parent of source node. But in source code *src/dom/list-item.js* line 306:310, it does not looks like targetNode is the parent of sourceNode. It is the sibling. 

````
                // Determine the new index
                newIndex = dir === 1 ? ++targetIndex : targetIndex;

                // Insert and cache the node
                newNode = targetNode.context().insertAt(newIndex, exported);
                ...
                this.props.dom._tree.emit('node.drop', event, newNode, targetNode, newIndex);
````

Should it return targetNode.context() instead of targetNode ?

**Comment by viveleroi** [comment]
`targetNode` is the node being targeted by the user. It would be a sibling node when you're dragging into an existing hierarchy, you'll drop the new node before or after the target/sibling. If you're dragging to a node without any children yet, the target will be the parent.
