### ISSUE TITLE
Method to override default html

### ISSUE THREAD

**Issue by yjchen** [helion3/inspire-tree-dom#23]
I wonder whether it is possible to override default html for nodes. I know I can fork the project and change the source code, but it is too much this purpose. Currently each node is render as **li** > **div**.title-wrap > **a**. 

What's the best way to add more html element probably under **div** tag ?

**Comment by viveleroi** [comment]
There really isn't a way to do this, aside from forking this repo and modifying the source. This is one of the reasons that the dom code is a separate project and can be replaced.

**Comment by valentinbdv** [comment]
Hey I will be interested in doing the same thing. Maybe we could have an html option instead of text in order to make the nodes more customizable?
