### ISSUE TITLE
use the modularized versions of lodash functions rather than pulling in the whole library

### ISSUE THREAD

**Issue by mreinstein** [helion3/inspire-tree-dom#27]
rather than importing the whole lodash kitchen sink, it would be really nice if we used the individually packaged functions. e.g.,:

`import * as _map from 'lodash.map'`

Besides making the bundles smaller this will also make it more explicit in the code which functions of lodash we're depending on.

If this is something you'd be open to, happy to send a PR. 👍

**Comment by viveleroi** [comment]
Unfortunately, modularized lodash causes more problems for people not using bundlers, because there's no way to map modularized imports to a property from a single library. I've been looking for a way to make it work but none of the bundlers  allow this kind of globals mapping, and requirejs has no way to do it.

https://github.com/helion3/inspire-tree/issues/168

**Comment by mreinstein** [comment]
I guess I don't understand; you bundle your own distributions right? As long as _your_ bundler works it should produce everything all packaged up correctly for people not using a bundler, right? or am I misisng something else?

**Comment by mreinstein** [comment]
@viveleroi I think there might be some confusion; each lodash function is it's own unique module in npm. e.g.: https://www.npmjs.com/package/lodash.find

as a result this shouldnt be any different from doing `import * as _ from 'lodash'`

**Comment by viveleroi** [comment]
There's no confusion. There's just no perfect answer. Sure, I *could* bundle lodash into my distribution files but not everyone bundles from our source and not everyone uses a bundler. If they don't use lodash, bundling on our end is a good solution. If they *do* use lodash, bundling on our end means they're shipping a fair amount of duplicate code.

Bundling modules is better than bundling the entire lodash library, but it's not going to solve everyone's problems. Importing modules, but not bundling them, would *only* work for users with a bundling pipeline.

**Comment by mreinstein** [comment]
> There's just no perfect answer. If they do use lodash, bundling on our 
> end means they're shipping a fair amount of duplicate code.

That's true there's no perfect answer. There is a pretty well established tradeoff though: you can either:

a - use some form of "real" dependency management, either by fancy new `import` syntax, or by amd.js, or by require + bundling, which means you get perfect re-use.

b - throw static script tags in your page and deal with the fact that you might have overlap, because library authors have no way of knowing what else is being thrown on the page or what is in the other tags.

This is a pretty reasonable tradeoff and it's part of the reason why module loading is becoming more common.

I'm not saying this to be argumentative, it's just that the current structure favors script globals. We're effectively punishing people that take the modular approach to building front ends.

**Comment by mreinstein** [comment]
fair enough 👍 Thanks for the clarifiation!

this issue is less important to me than the PR I've got in. If we can get that merged it solves my problem.  🙏
