### ISSUE TITLE
empty folders render strangely

### ISSUE THREAD

**Issue by mreinstein** [helion3/inspire-tree-dom#3]
I took the example tree on the inspire-tree.com website and dragged all of the items out of one of the folders. Here's what the result looks like:

<img width="401" alt="screen shot 2017-09-02 at 4 52 59 pm" src="https://user-images.githubusercontent.com/718067/29999474-3d04984e-8fff-11e7-987c-ebae1c8c9d8e.png">

**Comment by mreinstein** [comment]
If the folder is empty it would be nice if it drew the `.....` connector like it does for non-container entries. It would also be nice if that little `...` that hangs off an empty folder was hidden.

**Comment by viveleroi** [comment]
Until this is released, please be aware this depends on https://github.com/helion3/inspire-tree/commit/579de8286d9d212f4a2c4a2ad3f170a9748222e0.
