### ISSUE TITLE
Dynamic pagination

### ISSUE THREAD

**Issue by mjesteve** [helion3/inspire-tree-dom#32]
Hello,
I have made several queries on Gitter but there is never anyone and I don't know if it is cancelled or still working.
I am going to make my query here and if it is not correct please tell me.

I need the pagination to be dynamic and it only works if I recreate the component. I have tried to modify the config variable of InspireTree and InspireTreeDOM but that is not enough?

How should I do it?

Thank you.

**Comment by viveleroi** [comment]
Can you clarify what you mean by "dynamic pagination"? What do you expect to happen, and what actually is?

**Comment by mjesteve** [comment]
Hi @viveleroi, thanks for replying.

By dynamic paging I mean that the user, or any other process, can choose whether to "enable" paging or "disable" it after the component is created. If I recreate the component I lose the original instance and I need to keep it.

Hiedra.

**Comment by viveleroi** [comment]
Unfortunately, the configuration options weren't designed to be changed after instantiation. The config object is copied internally and during instantiation features are enabled/disabled and requirements are adjusted. Some config options are only read when needed, though.

You can try looking at the `config` property on your tree instance. Changing the value of `tree.config.deferredLoading  = true` (or whichever config values you're changing) might work. I would bet that pagination doesn't work well with toggling the config values like this, but I've never tried. I'd have to look through the code the refresh my memory.

**Comment by mjesteve** [comment]
Yes, I tried some combinations but they didn't work. Debugging the code I could see what you say, but I'm just starting with JS and I didn't know if I had interpreted it right...

I'm trying to create a wrapper for Apache Royale, I really liked your component and I thought it could be useful for me and other users.

Thx Mike.

**Comment by mjesteve** [comment]
Look, it's not bad... 

![GIF 16-10-2021 22-33-19](https://user-images.githubusercontent.com/55754195/137601484-6b3d6dc7-dc19-4313-81a0-9cf1d0d5f67d.gif)

**Comment by viveleroi** [comment]
Looks good. Can you leave some details about how you did it, in case anyone needs to do the same and finds this?

**Comment by mjesteve** [comment]
Sorry, I'm still building the wrapper... for now I've only implemented the basics:

```
	[ treeModel.configOptionView <-- property 'opts' InspireTreeDOM ]
	[ treeModel.configOption         <-- property 'opts' InspireTree ]
```

- Enabling "paging":  
```
	treeModel.configOptionView.nodeHeight = itemRendererHeight;
	treeModel.configOptionView.deferredRendering = true;
	treeModel.configOptionView.autoLoadMore = true;
		
	treeModel.configOption.pagination = {limit: numNodesPage};
```

- Disable "paging":
```
	treeModel.configOptionView.deferredRendering = false;
	treeModel.configOptionView.autoLoadMore = false;
	treeModel.configOption.pagination = {limit: -1};	
```

And then I recreate the component:
```
	objtree = new InspireTree(treeModel.configOption);
	objtreeDOM = new InspireTreeDOM(objtree, treeModel.configOptionView);
```
