### ISSUE TITLE
Drag and drop doesn't work in interaction with checkboxes

### ISSUE THREAD

**Issue by markwestcott34** [helion3/inspire-tree-dom#8]
There seems to be a problem when trying to use both drag and drop and checkboxes: drag and drop ceases to function once 'showCheckboxes' is enabled and results in errors on the console.

Here's my code (adapted from the checkbox.html demo)

```
   require([
            'jquery',
            'lodash',
            'inspire-tree',
            'inspire-tree-dom'
        ], function($, _, InspireTree, InspireTreeDOM) {

            var tree2 = new InspireTree({
                data: $.getJSON('sample-data/full.json'),
            });

            new InspireTreeDOM(tree2, {
                target: '.checkbox-tree',
                showCheckboxes: true,
                dragAndDrop: true
            });
        });
```

results in these errors in the console:

```
Uncaught TypeError: Cannot set property 'indeterminate' of null
    at inspire-tree-dom.js:3312
    at unmount (inspire-tree-dom.js:990)
    at unmount (inspire-tree-dom.js:968)
    at unmount (inspire-tree-dom.js:998)
    at unmount (inspire-tree-dom.js:998)
    at unmount (inspire-tree-dom.js:968)
    at patchKeyedChildren (inspire-tree-dom.js:1602)
    at patchChildren (inspire-tree-dom.js:1337)
    at patchElement (inspire-tree-dom.js:1209)
    at patch (inspire-tree-dom.js:1149)
```

**Comment by viveleroi** [comment]
Sorry for the delay but I've been looking into this, and don't yet have a good solution. InspireTreeDOM uses InfernoJS for the dom engine but there's an unusual problem after dropping a node in which the render function gives us a bad reference to the element. I'm trying to look into why, but it's going to need input from them, which I'm waiting on.

**Comment by viveleroi** [comment]
Actually I just did a better trace and I realize the problem. However, there's a larger issue in that dragged nodes lose their state (checked values get lost, for example), so I'll provide a fix for this issue, but I'll release an update soon that also includes the fix for checked states being lost.
